services:
  - type: web
    name: tp-render-node
    env: node
    plan: free
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: DB_URL
        fromDatabase:
          name: tp-render-node-db
          property: connectionString



databases:
  - name: tp-render-node-db
    plan: free
 
    
